package at.rtr.rmbt;

import at.rtr.rmbt.enums.TestType;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.UUID;

public interface TestConstants {
    String DEFAULT_LANGUAGE = "DEFAULT LANGUAGE";
    Long DEFAULT_LAST_NEWS_UID = 13L;
    String DEFAULT_PLATFORM = "DEFAULT PLATFORM";
    Long DEFAULT_SOFTWARE_VERSION_CODE = 1L;
    UUID DEFAULT_NEWS_UUID = UUID.fromString("8fa5fb1c-5bf6-11eb-ae93-0242ac130002");
    UUID DEFAULT_UUID = UUID.fromString("88ab584e-5ef2-11eb-ae93-0242ac130002");
    Long DEFAULT_UID = 2L;
    String DEFAULT_NEWS_TITLE = "DEFAULT NEWS TITLE";
    String DEFAULT_NEWS_TEXT = "DEFAULT NEWS TEXT";
    UUID DEFAULT_TEST_SERVER_UUID = UUID.fromString("f79b66b5-6420-4336-ab6d-69ad4158fa1b");
    String DEFAULT_TEST_SERVER_NAME = "DEFAULT TEST SERVER NAME";
    String DEFAULT_TEST_SERVER_WS_NAME = "DEFAULT TEST SERVER WS NAME";
    String DEFAULT_TEST_SERVER_QOS_NAME = "DEFAULT TEST SERVER QOS NAME";
    String DEFAULT_QOS_TEST_TYPE_DESC_NAME = "DEFAULT QOS TEST TYPE DESC NAME";
    TestType DEFAULT_TEST_TYPE = TestType.DNS;
    Long DEFAULT_TERM_AND_CONDITION_VERSION = 2L;
    String DEFAULT_TERM_AND_CONDITION_URL = "DEFAULT TERM AND CONDITION URL";
    String DEFAULT_TERM_AND_CONDITION_NDT_URL = "DEFAULT TERM AND CONDITION NDT URL";
    String DEFAULT_URLS_URL_SHARE = "DEFAULT URLS URL SHARE";
    String DEFAULT_URLS_IPV6_CHECK = "DEFAULT URLS IPV6 CHECK";
    String DEFAULT_URLS_CONTROL_IPV4_ONLY = "DEFAULT URLS CONTROL IPV4 ONLY";
    String DEFAULT_URLS_OPEN_DATA_PREFIX = "DEFAULT URLS OPEN DATA PREFIX";
    String DEFAULT_URLS_URL_MAP_SERVER = "DEFAULT URLS URL MAP SERVER";
    String DEFAULT_URLS_URL_IPV4_CHECK = "DEFAULT URLS URL IPV4 CHECK";
    String DEFAULT_URLS_CONTROL_IPV6_ONLY = "DEFAULT URLS CONTROL IPV6 ONLY";
    String DEFAULT_URLS_STATISTICS = "DEFAULT URLS STATISTICS";
    String DEFAULT_CONTROL_SERVER_VERSION = "DEFAULT CONTROL SERVER VERSION";
    String DEFAULT_SERVER_UUID = "DEFAULT_SERVER_UUID";
    String DEFAULT_SERVER_WS_UUID = "DEFAULT_SERVER_WS_UUID";
    String DEFAULT_SERVER_QOS_UUID = "DEFAULT_SERVER_QOS_UUID";
    String DEFAULT_HISTORY_DEVICE = "DEFAULT HISTORY DEVICE";
    String DEFAULT_HISTORY_NETWORK = "DEFAULT HISTORY NETWORK";
    UUID DEFAULT_CLIENT_UUID = UUID.fromString("9e1ccb36-59e3-11eb-ae93-0242ac130002");
    UUID DEFAULT_CLIENT_UUID_GENERATED = UUID.fromString("b5455118-5af9-11eb-ae93-0242ac130002");
    Long DEFAULT_MAP_SERVER_PORT = 443L;
    String DEFAULT_MAP_SERVER_HOST = "DEFAULT MAP SERVER HOST";
    boolean DEFAULT_FLAG_TRUE = true;
    String DEFAULT_IP_HEADER = "DEFAULT IP HEADER";
    String DEFAULT_CLIENT_NAME = "RMBT";
    String DEFAULT_TEXT = "DEFAULT TEXT";
    OffsetDateTime DEFAULT_OFFSET_DATE_TIME_TIMESTAMP = OffsetDateTime.of(LocalDateTime.of(2021, 1, 20, 7, 32), ZoneOffset.ofHoursMinutes(4, 0));
    String DEFAULT_TC_URL_ANDROID_VALUE = "DEFAULT_TC_URL_ANDROID_VALUE";
    String DEFAULT_TC_NDT_URL_ANDROID_VALUE = "DEFAULT_TC_NDT_URL_ANDROID_VALUE";
    String DEFAULT_TC_VERSION_ANDROID_VALUE = Long.valueOf(5).toString();
    String DEFAULT_TC_URL_ANDROID_V4_VALUE = "DEFAULT_TC_URL_ANDROID_V4_VALUE";
    String DEFAULT_TC_URL_IOS_VALUE = "DEFAULT_TC_URL_IOS_VALUE";
    String DEFAULT_TC_VERSION_IOS_VALUE = Long.valueOf(3).toString();
    String DEFAULT_TC_VERSION_VALUE = Long.valueOf(9).toString();
    String DEFAULT_TC_URL_VALUE = "DEFAULT_TC_URL_VALUE";
    String DEFAULT_ANDROID_PLATFORM = "ANDROID";
    String DEFAULT_IOS_PLATFORM = "IOS";
    String DEFAULT_CLIENT_TYPE_NAME = "DEFAULT_CLIENT_TYPE_NAME";
    String DEFAULT_NEWS_TITLE_DE = "DEFAULT_NEWS_TITLE_DE";
    String DEFAULT_NEWS_TEXT_DE = "DEFAULT_NEWS_TEXT_DE";
    String DEFAULT_NEWS_TITLE_EN = "DEFAULT_NEWS_TITLE_EN";
    String DEFAULT_NEWS_TEXT_EN = "DEFAULT_NEWS_TEXT_EN";
    String DEFAULT_INSTANT_EXPECTED = "2021-12-03T10:15:30.00Z";
    Long DEFAULT_MAX_SOFTWARE_VERSION = 5L;
    Long DEFAULT_MIN_SOFTWARE_VERSION = 3L;
    String DEFAULT_SETTINGS_KEY = "tc_url";
    Long DEFAULT_TIME = 110000L;
    String DEFAULT_TIMEZONE = "Europe/Bratislava";
    String DEFAULT_PROVIDER = "DEFAULT_PROVIDER";
    String DEFAULT_IP = "37.57.0.215";
    String DEFAULT_RESULT_URL = "DEFAULT_RESULT_URL";
    String DEFAULT_URL = "DEFAULT_RESULT_URL";

    interface Database {
        long CLIENT_TYPE_DESKTOP_UID = 1L;
        long CLIENT_TYPE_MOBILE_UID = 2L;
        UUID TEST1_UUID = UUID.fromString("48ddf306-3f55-4e28-a657-22dd7790921d");
        UUID CLIENT1_UUID = UUID.fromString("13d8667a-ddbc-40c9-95c9-93933087ec30");
        String PROVIDER_A1_TELECOM_SHORT_NAME = "A1 TA";
    }
}
