package at.rtr.rmbt.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Getter;

@Getter
@Builder
public class IpRequest {

    @Schema(description = "Client uuid")
    @JsonProperty(value = "client_uuid")
    private final String clientUUID;

    @Schema(description = "Language code of the current locale (ISO 639)")
    @JsonProperty(value = "client_language")
    private final String clientLanguage;

    @Schema(description = "Local IP of client (Ipv4 or IPv6)")
    @JsonProperty(value = "client_ip_local")
    private final String clientIpLocal;

    @Schema(description = " Test UUID generated by control server", example = "f71d53f4-c67c-4b99-b319-979f714cd408")
    @JsonProperty(value = "test_uuid")
    private final String testUUID;

}
