package at.rtr.rmbt.enums;

public enum TestStatus {
    ABORTED, END, ERROR, ERROR_DOWN, ERROR_INIT, ERROR_UP, FINISHED, SIGNAL, STARTED, SIGNAL_STARTED, ERROR_PING, ERROR_INIT_UP, ERROR_WAIT, ERROR_FETCH, ERROR_SPEEDTEST_END, NONE, ERROR_SUBMIT, ABORTED_BACKGROUNDED, COVERAGE_STARTED, COVERAGE
}
