package at.rtr.rmbt.enums;

public enum TestStatus {
    ABORTED, END, ERROR, ERROR_DOWN, ERROR_INIT, ERROR_UP, FINISHED, SIGNAL, STARTED, SIGNAL_STARTED, ERROR_INIT_UP, ERROR_WAIT, ERROR_SPEEDTEST_END
}
